# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 30 Nov 2021 10:30:02 +0000
*	@user	1
*	@editor	16
其他:*	@editor	1
*	@ALL	1
sidebar	@ALL	1
sidebar	@user	1
