<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: yx5932
 * Date: Thu, 02 Dec 2021 18:31:05 +0800
 */

$conf['title'] = '《LoR符文之地传说》 中文百科';
$conf['start'] = '主页';
$conf['lang'] = 'zh';
$conf['tagline'] = '写什么副标题好呢';
$conf['sidebar'] = '导航栏';
$conf['license'] = 'cc-by-sa';
$conf['youarehere'] = 1;
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '5';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;
$conf['target']['extern'] = '_blank';
$conf['defer_js'] = 0;
$conf['proxy']['user'] = 'yx5932';
$conf['proxy']['pass'] = '<b>eWFueGluODUyNDY=';
$conf['plugin']['gallery']['image_width'] = 1024;
$conf['plugin']['gallery']['image_height'] = 768;
$conf['plugin']['imagebox']['display_magnify'] = 'Never';
$conf['plugin']['indexmenu']['skip_index'] = '/ (wiki:*) /';
$conf['plugin']['indexmenu']['skip_file'] = '/ (wiki:*) /';
$conf['plugin']['simplenavi']['sort'] = 'ascii';
