# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 30 Nov 2021 10:30:02 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

yx5932:$2y$10$EzEk2eU87tTP1O5BRBO6ruBeLyK5ixhoq80gQQYeIImP5UxLwVMo6:Xin Yan:593261870@qq.com:admin,user
yx59322:$2y$10$ZYcdoxmLT2DoslePZta78e5Jubqj78Ifk1XmryOfFtC27SudUp96O:yx5932:593261870@qq.com:editor,user
